---
# tasks file for roles/web

- name: Install required packages
  become: yes
  yum:
    name: httpd, php, php-mysql
    state: present

- name: Add port db to firewall
  become: yes
  firewalld:
    port: 80/tcp
    permanent: yes
    zone: public
    state: enabled

- name: Reload service firewalld
  become: yes
  service:
    name: firewalld
    state: reloaded

- name: Start service httpd
  become: yes
  service:
    name: httpd
    state: started
    enabled: yes

- name: Replace ip by localhost
  become: yes
  lineinfile:
    path: /var/www/html/index.php
    regexp: '^172\.20\.1\.101$'
    line: 'localhost'
