---
# ==============================================================================
# Do basic firewallD setup for all hosts
# ==============================================================================
- hosts: all

  roles:
    - firewalld

# ==============================================================================
# Do basic database setup for all hosts
# ==============================================================================
- hosts: all
  become: yes

  roles:
    - database

# ==============================================================================
# Do basic web setup and deploy for all hosts
# ==============================================================================
- hosts: all
  become: yes

  roles:
    - web
